name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Build Docker image
        run: docker build -t myapp .
      
      - name: Start Docker container
        run: docker run -d -p 8000:8000 --name myapp_container myapp
      
      - name: Run tests
        run: python test.py
      
      - name: Stop Docker container
        run: docker stop myapp_container
      
      - name: Post test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test_results/
